---

- name: Deploy app
  hosts: all
  become: true
  pre_tasks:

    - name: Update system
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true

- name: Install docker and docker compose
  hosts: all
  become: true
  roles:
    - docker

- name: Deploy app
  hosts: app
  become: true
  roles:
    - app

- name: Setup nginx
  hosts: nginx
  become: true
  roles:
    - nginx
