- name: Create directory for monitoring
  ansible.builtin.file:
    path: /opt/monitoring
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Copy prometheus config
  ansible.builtin.template:
    src: "{{ prometheus_config_template_file }}"
    dest: /opt/monitoring/prometheus.yml
    owner: root
    group: root
    mode: "0644"

- name: Copy docker compose file for monitoring
  ansible.builtin.copy:
    src: compose.yml
    dest: /opt/monitoring/compose.yml
    owner: root
    group: root
    mode: "0644"

- name: Create prometheus directory
  ansible.builtin.file:
    path: /opt/monitoring/prometheus
    state: directory
    owner: "65534"
    group: "65534"
    mode: "0755"

- name: Create grafana directory
  ansible.builtin.file:
    path: /opt/monitoring/grafana
    state: directory
    owner: "472"
    group: "472"
    mode: "0755"

- name: Start docker compose
  community.docker.docker_compose_v2:
    project_src: /opt/monitoring/
    state: present
    recreate: always
