- name: Create directory for app
  ansible.builtin.file:
    path: /opt/app
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Copying app files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /opt/app/
    owner: root
    group: root
    mode: "0644"
  loop:
    - Dockerfile
    - main.py
    - requirements.txt
    - compose.yml

- name: Set default incoming policy to deny
  community.general.ufw:
    direction: incoming
    policy: deny

- name: Allow SSH
  community.general.ufw:
    rule: allow
    port: "22"
    proto: tcp

- name: Allow HTTP
  community.general.ufw:
    rule: allow
    port: "80"
    proto: tcp

- name: Allow monitoring server to access node_exporter via Docker
  ansible.builtin.iptables:
    chain: DOCKER-USER
    protocol: tcp
    destination_port: "9100"
    source: "{{ hostvars[groups['monitoring'][0]].ansible_host }}"
    jump: ACCEPT
    action: insert
    rule_num: 1

- name: Block other access to node_exporter via Docker
  ansible.builtin.iptables:
    chain: DOCKER-USER
    protocol: tcp
    destination_port: "9100"
    jump: DROP
    action: insert
    rule_num: 2

- name: Enable ufw
  community.general.ufw:
    state: enabled

- name: Start docker compose
  community.docker.docker_compose_v2:
    project_src: "/opt/app/"
    state: present
