name: Deploy infrastructure

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Setup ssh key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Create inventory
        run: |
          cat > inventory <<EOF
          [nginx]
          vm1 ansible_host=${{ secrets.VM1_IP }}

          [app]
          vm2 ansible_host=${{ secrets.VM2_IP }}
          vm3 ansible_host=${{ secrets.VM3_IP }}

          [monitoring]
          vm4 ansible_host=${{ secrets.VM4_IP }}
          EOF
      - name: Create config
        run: |
          cat > ansible.cfg <<EOF
          [defaults]
          inventory=inventory
          remote_user="{{ secrets.SSH_USER }}"
          private_key_file=~/.ssh/id_ed25519
          EOF
      - name: Add hosts to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.VM1_IP }} >> ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.VM2_IP }} >> ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.VM3_IP }} >> ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.VM4_IP }} >> ~/.ssh/known_hosts
      
      - name: Run ansible playbook
        run: |
          ansible-playbook deploy.yml